In [1]:
import torch

In [6]:
torch.__version__

'2.8.0+cu128'

In [7]:
# scalar 
scalar  = torch.tensor(8)
scalar

tensor(8)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

8

In [10]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
#matrix
matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[2,4,5]]])

In [18]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
# random
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.6382, 0.6775, 0.7096, 0.2933],
        [0.4383, 0.6466, 0.8310, 0.2009],
        [0.1764, 0.1826, 0.6529, 0.8653]])

In [23]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,  random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
#zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [26]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
# default datatypes for tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor,  float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [32]:
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
some_tensor = torch.rand(3,4)
some_tensor,  some_tensor.shape, some_tensor.device, some_tensor.dtype

(tensor([[0.7745, 0.0850, 0.1084, 0.4056],
         [0.6224, 0.2403, 0.3745, 0.1640],
         [0.3765, 0.2139, 0.1461, 0.7991]]),
 torch.Size([3, 4]),
 device(type='cpu'),
 torch.float32)

In [35]:
tensor = torch.tensor([1,2,3])

In [36]:
tensor + 10

tensor([11, 12, 13])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor - 10

tensor([-9, -8, -7])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [42]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [43]:
torch.sub(10, tensor)

tensor([9, 8, 7])

In [45]:
tensor * tensor

tensor([1, 4, 9])

In [46]:
tensor.matmul(tensor)

tensor(14)

In [47]:
tensor @ tensor

tensor(14)

In [49]:
%%time
tensor @ tensor

CPU times: user 252 μs, sys: 0 ns, total: 252 μs
Wall time: 262 μs


tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.35 ms, sys: 4.91 ms, total: 6.26 ms
Wall time: 31.5 ms


tensor(14)

In [52]:
len(tensor)

3

In [53]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])
tensor_b = torch.tensor([[7,10],[8,11],[9,12]])

In [54]:
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [55]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [58]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [60]:
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_a.float()
output = linear(x)
x.shape, output, output.shape

(torch.Size([3, 2]),
 tensor([[-0.7368,  0.5661, -0.0143, -1.8574,  0.0377, -0.1177],
         [-0.1544,  1.3958,  0.1210, -3.2849,  0.0376, -1.1581],
         [ 0.4280,  2.2256,  0.2563, -4.7123,  0.0375, -2.1984]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]))

In [61]:
x.min(), x.max()

(tensor(1.), tensor(6.))

In [62]:
x.type(torch.float16).mean()

tensor(3.5000, dtype=torch.float16)

In [63]:
x.sum()

tensor(21.)

In [64]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [65]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [66]:
x, x.dtype

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.float32)

In [69]:
tensor = torch.arange(10,100,10)
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
tensor_float16 = tensor.type(torch.float16)

In [71]:
tensor_float16.dtype

torch.float16

In [72]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8, tensor_int8.dtype

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8), torch.int8)

In [73]:
x = torch.arange(1,8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [75]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [77]:
z = x.view(1,7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [78]:
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1, 2, 3, 4, 5, 6, 7],
         [1, 2, 3, 4, 5, 6, 7],
         [1, 2, 3, 4, 5, 6, 7],
         [1, 2, 3, 4, 5, 6, 7],
         [1, 2, 3, 4, 5, 6, 7]]),
 torch.Size([5, 7]))

In [79]:
x_reshaped, x_reshaped.shape
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [80]:
x_unsqueeze = torch.unsqueeze(x_squeezed,dim=0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [81]:
x_origianl = torch.rand(224,235,3)

In [83]:
x_permuted = x_origianl.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 235])

In [84]:
x = torch.arange(1,10).reshape(1,3,3)

In [85]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [86]:
x[:,0]

tensor([[1, 2, 3]])

In [87]:
x[:,1,1]

tensor([5])

In [88]:
import numpy as np

In [89]:
array = np.arange(1,8)

In [90]:
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [92]:
random_a = torch.rand(3,4)
random_b = torch.rand(3,4)
random_a == random_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [93]:
RADOM_SEED = 42
torch.manual_seed(RADOM_SEED)
random_c = torch.rand(3,4)
torch.manual_seed(RADOM_SEED)
random_d = torch.rand(3,4)
random_c == random_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [94]:
torch.cuda.is_available()

False

In [96]:
device = 'cuda' if torch.cuda.is_available() else'cpu'
device

'cpu'

In [97]:
torch.cuda.device_count()

0

In [98]:
torch.backends.mps.is_available()

False

In [100]:
def get_dev():
    if torch.cuda.is_available():
        return 'cuda'
    elif torch.backends.mps.is_available():
        return 'mps'
    else:
        return 'cpu'

get_dev()

'cpu'

In [101]:
get_dev()

'cpu'

In [102]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [103]:
tensor_gpu = tensor.to(get_dev())

In [104]:
tensor_gpu.device

device(type='cpu')

In [105]:
tensor.cpu()

tensor([1, 2, 3])